const SUPABASE_URL='https://bfrofclxcjpufqpfyqiz.supabase.co';
const SUPABASE_KEY='sb_publishable_oXyVQBSbjW64hotxW2G-BA_akx34fk1';
const CATEGORIES=['Agricultura','Alimentação','Comércio','Construção','Educação','Eventos','Finanças','Saúde','Serviços','Tecnologia','Transporte','Turismo'];
const state={session:null,user:null,profile:null,opportunities:[],ads:[],favorites:new Set(),proposals:[],messages:[]};
const $=id=>document.getElementById(id);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const sessionKey='link_direto_session_v2';

document.addEventListener('DOMContentLoaded',async()=>{
  fillCategories();
  updatePublishPreview();
  try{state.session=JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{}
  if(state.session?.access_token){await restoreSession()}
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
});

function fillCategories(){
  const options=CATEGORIES.map(c=>`<option>${c}</option>`).join('');
  $('pCategory').innerHTML=options;$('businessCategory').innerHTML=options;
  $('searchCategory').innerHTML='<option value="">Todas categorias</option>'+options;
}
function enterApp(){$('splash').classList.add('hidden');$('app').classList.remove('hidden');loadPublicData()}
function showView(name,button){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+name).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'));(button||document.querySelector(`[data-view="${name}"]`))?.classList.add('active');scrollTo(0,0);if(name==='connect')loadConnect();if(name==='profile')renderProfile()}
function openPublish(type='tenho'){showView('publish');document.querySelector(`input[name="ptype"][value="${type}"]`).checked=true;if(!state.user)openAuth()}
function handleAccountClick(){state.user?showView('profile'):openAuth()}
function toast(message,error=false){const t=$('toast');t.textContent=message;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',3200)}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden');$('modalContent').innerHTML=''}
function authHeaders(json=true){const h={apikey:SUPABASE_KEY};if(json)h['Content-Type']='application/json';if(state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;return h}
async function api(table,query='',options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`,{...options,headers:{...authHeaders(options.body instanceof FormData?false:true),...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}

function openAuth(mode='login'){
  openModal(`<h2>Conta empresarial</h2><p class="muted">Entra para publicar, enviar propostas e conversar.</p><div class="tabs"><button id="loginTab" class="${mode==='login'?'active':''}" onclick="openAuth('login')">Entrar</button><button class="${mode==='signup'?'active':''}" onclick="openAuth('signup')">Criar conta</button></div><form onsubmit="${mode==='login'?'login':'signup'}(event)">${mode==='signup'?'<label>Nome do negócio<input id="authBusiness" required maxlength="80"></label>':''}<label>E-mail<input id="authEmail" type="email" required autocomplete="email"></label><label>Senha<input id="authPassword" type="password" required minlength="6" autocomplete="current-password"></label><button class="btn primary">${mode==='login'?'Entrar':'Criar conta'}</button></form>`)
}
async function signup(e){e.preventDefault();try{const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:'POST',headers:authHeaders(),body:JSON.stringify({email:$('authEmail').value,password:$('authPassword').value,data:{business_name:$('authBusiness').value}})});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.message);if(d.access_token){setSession(d);await afterLogin()}else{toast('Conta criada. Confirma o e-mail e depois entra.');closeModal()}}catch(err){toast(readableError(err),true)}}
async function login(e){e.preventDefault();try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:authHeaders(),body:JSON.stringify({email:$('authEmail').value,password:$('authPassword').value})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||d.message);setSession(d);await afterLogin();toast('Sessão iniciada com sucesso.')}catch(err){toast(readableError(err),true)}}
function setSession(d){state.session=d;state.user=d.user;localStorage.setItem(sessionKey,JSON.stringify(d))}
async function restoreSession(){try{const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(false)});if(!r.ok)throw new Error();state.user=await r.json();await loadProfile();updateAccountUI()}catch{localStorage.removeItem(sessionKey);state.session=null;state.user=null}}
async function afterLogin(){closeModal();await loadProfile();await loadFavorites();updateAccountUI();renderProfile();loadPublicData()}
async function logout(){try{await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:authHeaders(false)})}catch{}localStorage.removeItem(sessionKey);state.session=null;state.user=null;state.profile=null;state.favorites.clear();updateAccountUI();renderProfile();showView('home');toast('Sessão terminada.')}
function updateAccountUI(){$('accountButton').textContent=state.profile?.business_name?.split(' ')[0]||'Entrar'}
function readableError(err){const s=String(err.message||err);if(s.includes('Invalid login'))return'E-mail ou senha incorretos.';if(s.includes('already registered'))return'Este e-mail já está registado.';return'Não foi possível concluir. Confirma os dados e tenta novamente.'}

async function loadProfile(){if(!state.user)return;try{const d=await api('profiles',`?id=eq.${state.user.id}&select=*`);state.profile=d?.[0]||null;if(!state.profile){await api('profiles','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:state.user.id,business_name:state.user.user_metadata?.business_name||'Meu negócio'})});const p=await api('profiles',`?id=eq.${state.user.id}&select=*`);state.profile=p?.[0]}}catch(err){console.error(err)}}
function renderProfile(){const logged=!!state.user;$('profileGuest').classList.toggle('hidden',logged);$('profileForm').classList.toggle('hidden',!logged);if(!logged)return;const p=state.profile||{};$('businessName').value=p.business_name||'';$('businessCategory').value=p.category||CATEGORIES[0];$('businessLocation').value=p.location||'';$('businessPhone').value=p.phone||'';$('businessBio').value=p.bio||'';$('profileName').textContent=p.business_name||'Meu negócio';$('profileAvatar').textContent=(p.business_name||'LD').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();if($('cardCategory'))$('cardCategory').textContent=p.category||'Categoria';if($('cardLocation'))$('cardLocation').textContent=p.location||'Moçambique';const score=40+(p.location?10:0)+(p.phone?10:0)+(p.bio?10:0);$('profileScore').textContent=`Link Score ${score}`}
async function saveProfile(e){e.preventDefault();if(!requireAuth())return;const body={business_name:$('businessName').value.trim(),category:$('businessCategory').value,location:$('businessLocation').value.trim(),phone:$('businessPhone').value.trim(),bio:$('businessBio').value.trim(),updated_at:new Date().toISOString()};try{await api('profiles',`?id=eq.${state.user.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});state.profile={...state.profile,...body};updateAccountUI();renderProfile();toast('Perfil atualizado.')}catch(err){toast('Não foi possível guardar o perfil.',true)}}
function requireAuth(){if(state.user)return true;openAuth();toast('Entra primeiro na tua conta.');return false}

async function loadPublicData(){try{const [opps,ads]=await Promise.all([api('opportunities','?select=*&order=created_at.desc&limit=100'),api('advertisements','?select=*&status=eq.active&order=created_at.desc&limit=20')]);state.opportunities=opps||[];state.ads=ads||[];if(state.user)await loadFavorites();renderHome();renderSearch();renderAds()}catch(err){console.error(err);$('homeFeed').innerHTML='<div class="empty">Não foi possível carregar. Executa primeiro o ficheiro ATUALIZAR_SUPABASE_COMPLETO.sql.</div>'}}
async function loadFavorites(){if(!state.user)return;try{const d=await api('favorites',`?user_id=eq.${state.user.id}&select=opportunity_id`);state.favorites=new Set((d||[]).map(x=>String(x.opportunity_id)))}catch{}}
function opportunityCard(o){const saved=state.favorites.has(String(o.id));const mine=state.user&&o.user_id===state.user.id;return `<article class="card">${o.image_url?`<img class="card-media" src="${esc(o.image_url)}" alt="">`:''}<div class="card-body"><div class="card-top"><span class="tag ${o.type==='tenho'?'green':''}">${esc((o.type||'preciso').toUpperCase())} • ${esc(o.category)}</span>${o.status==='closed'?'<span class="tag">Fechado</span>':''}</div><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div class="meta"><span>📍 ${esc(o.location)}</span><span>⏱ ${formatDate(o.created_at)}</span></div><div class="card-actions">${mine?`<button class="btn secondary" onclick="manageOpportunity('${o.id}')">Gerir anúncio</button>`:`<button class="btn primary" onclick="openProposal('${o.id}','${o.user_id||''}')">Enviar proposta</button>`}<button class="icon-btn ${saved?'saved':''}" onclick="toggleFavorite('${o.id}')">★</button></div></div></article>`}
function renderHome(){$('homeFeed').innerHTML=state.opportunities.slice(0,6).map(opportunityCard).join('')||'<div class="empty">Ainda não existem oportunidades.</div>';$('homeAd').innerHTML=state.ads[0]?adCard(state.ads[0]):'';if($('statOpps'))$('statOpps').textContent=state.opportunities.length;if($('statAds'))$('statAds').textContent=state.ads.length}
function quickCategory(category){$('searchCategory').value=category;renderSearch()}
function updatePublishPreview(){const type=document.querySelector('input[name="ptype"]:checked')?.value?.toUpperCase()||'TENHO';const title=$('pTitle')?.value?.trim()||'O teu anúncio aparecerá aqui';const category=$('pCategory')?.value||'Categoria';const location=$('pLocation')?.value?.trim()||'Localização';if($('publishPreview'))$('publishPreview').innerHTML=`<small>${esc(type)} • ${esc(category)}</small><b>${esc(title)}</b><span>📍 ${esc(location)}</span>`}
function renderSearch(){const text=($('searchText')?.value||'').toLowerCase(),type=$('searchType')?.value||'',cat=$('searchCategory')?.value||'';const items=state.opportunities.filter(o=>(!type||o.type===type)&&(!cat||o.category===cat)&&(!text||`${o.title} ${o.description} ${o.location}`.toLowerCase().includes(text)));$('searchFeed').innerHTML=items.map(opportunityCard).join('')||'<div class="empty">Nenhuma oportunidade encontrada.</div>'}
function formatDate(v){if(!v)return'Agora';return new Date(v).toLocaleDateString('pt-PT',{day:'2-digit',month:'short'})}
async function uploadImage(file,bucket='opportunity-images'){if(!file)return null;if(!requireAuth())return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${state.user.id}/${Date.now()}-${safe}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok)throw new Error(await r.text());return`${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`}
async function submitOpportunity(e){e.preventDefault();if(!requireAuth())return;const button=e.submitter;button.disabled=true;button.textContent='A publicar...';try{const image_url=await uploadImage($('pImage').files[0]);const body={user_id:state.user.id,type:document.querySelector('input[name="ptype"]:checked').value,title:$('pTitle').value.trim(),category:$('pCategory').value,description:$('pDescription').value.trim(),location:$('pLocation').value.trim(),image_url,status:'active'};await api('opportunities','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});e.target.reset();toast('Publicação criada com sucesso.');await loadPublicData();showView('home')}catch(err){console.error(err);toast('Não foi possível publicar. Confirma a atualização do Supabase.',true)}finally{button.disabled=false;button.textContent='Publicar agora'}}
async function toggleFavorite(id){if(!requireAuth())return;try{if(state.favorites.has(String(id))){await api('favorites',`?user_id=eq.${state.user.id}&opportunity_id=eq.${id}`,{method:'DELETE'});state.favorites.delete(String(id))}else{await api('favorites','',{method:'POST',body:JSON.stringify({user_id:state.user.id,opportunity_id:id})});state.favorites.add(String(id))}renderHome();renderSearch()}catch{toast('Não foi possível guardar o favorito.',true)}}
function manageOpportunity(id){const o=state.opportunities.find(x=>String(x.id)===String(id));openModal(`<h2>Gerir publicação</h2><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><button class="btn secondary" onclick="setOpportunityStatus('${id}','${o.status==='closed'?'active':'closed'}')">${o.status==='closed'?'Reabrir':'Marcar como concluída'}</button><button class="btn ghost" onclick="deleteOpportunity('${id}')">Eliminar publicação</button>`)}
async function setOpportunityStatus(id,status){try{await api('opportunities',`?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status})});closeModal();await loadPublicData();toast('Publicação atualizada.')}catch{toast('Não foi possível atualizar.',true)}}
async function deleteOpportunity(id){if(!confirm('Eliminar esta publicação?'))return;try{await api('opportunities',`?id=eq.${id}`,{method:'DELETE'});closeModal();await loadPublicData();toast('Publicação eliminada.')}catch{toast('Não foi possível eliminar.',true)}}

function openProposal(opportunityId,ownerId){if(!requireAuth())return;if(!ownerId){toast('Esta publicação antiga não tem proprietário associado.',true);return}const o=state.opportunities.find(x=>String(x.id)===String(opportunityId));openModal(`<h2>Proposta Direta</h2><p>Para: <b>${esc(o?.title||'Oportunidade')}</b></p><form onsubmit="submitProposal(event,'${opportunityId}','${ownerId}')"><label>Mensagem<textarea id="proposalMessage" required placeholder="Explica o que podes oferecer..."></textarea></label><label>Valor estimado (opcional)<input id="proposalPrice" inputmode="decimal" placeholder="Ex.: 5 000 MZN"></label><label>Prazo (opcional)<input id="proposalDeadline" placeholder="Ex.: Entrega em 3 dias"></label><button class="btn primary">Enviar proposta</button></form>`)}
async function submitProposal(e,opportunityId,ownerId){e.preventDefault();const o=state.opportunities.find(x=>String(x.id)===String(opportunityId));try{await api('proposals','',{method:'POST',body:JSON.stringify({opportunity_id:opportunityId,opportunity_title:o?.title||'Oportunidade',sender_id:state.user.id,owner_id:ownerId,message:$('proposalMessage').value.trim(),price:$('proposalPrice').value.trim(),deadline:$('proposalDeadline').value.trim(),status:'pending'})});closeModal();toast('Proposta enviada.');loadConnect()}catch{toast('Não foi possível enviar a proposta.',true)}}
async function loadConnect(){if(!state.user){$('connectContent').innerHTML='<div class="empty">Entra na tua conta para veres propostas e conversas.</div>';return}try{state.proposals=await api('proposals',`?or=(sender_id.eq.${state.user.id},owner_id.eq.${state.user.id})&order=created_at.desc` )||[];$('pendingCount').textContent=state.proposals.filter(p=>p.status==='pending').length;$('acceptedCount').textContent=state.proposals.filter(p=>p.status==='accepted').length;$('messageCount').textContent=state.proposals.filter(p=>p.status==='accepted').length;$('connectContent').innerHTML=state.proposals.map(proposalCard).join('')||'<div class="empty">Ainda não existem propostas.</div>'}catch(err){console.error(err);$('connectContent').innerHTML='<div class="empty">Não foi possível carregar as propostas.</div>'}}
function proposalCard(p){const incoming=p.owner_id===state.user.id;return `<article class="card"><div class="card-body"><div class="card-top"><span class="tag ${p.status==='accepted'?'green':p.status==='pending'?'yellow':''}">${p.status==='pending'?'PENDENTE':p.status==='accepted'?'ACEITE':'RECUSADA'}</span><small>${incoming?'Recebida':'Enviada'}</small></div><h3>${esc(p.opportunity_title)}</h3><p>${esc(p.message)}</p><div class="meta"><span>${esc(p.price||'Valor a combinar')}</span><span>${esc(p.deadline||'Prazo a combinar')}</span></div><div class="card-actions">${incoming&&p.status==='pending'?`<button class="btn primary" onclick="updateProposal('${p.id}','accepted')">Aceitar</button><button class="icon-btn" onclick="updateProposal('${p.id}','rejected')">×</button>`:p.status==='accepted'?`<button class="btn primary" onclick="openChat('${p.id}','${incoming?p.sender_id:p.owner_id}')">Abrir conversa</button>`:'<button class="btn secondary" disabled>A aguardar resposta</button>'}</div></div></article>`}
async function updateProposal(id,status){try{await api('proposals',`?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status})});toast(status==='accepted'?'Proposta aceite. Chat aberto.':'Proposta recusada.');loadConnect()}catch{toast('Não foi possível atualizar.',true)}}
async function openChat(proposalId,otherId){const proposal=state.proposals.find(p=>String(p.id)===String(proposalId));try{state.messages=await api('messages',`?proposal_id=eq.${proposalId}&order=created_at.asc`)||[];openModal(`<h2>Sala de Negócio</h2><p>${esc(proposal?.opportunity_title||'Conversa')}</p><div id="chatMessages" class="chat">${renderMessages()}</div><form onsubmit="sendMessage(event,'${proposalId}','${otherId}')"><label>Mensagem<input id="chatInput" required autocomplete="off" placeholder="Escreve uma mensagem..."></label><button class="btn primary">Enviar</button></form>`);setTimeout(()=>{const c=$('chatMessages');c.scrollTop=c.scrollHeight},0)}catch{toast('Não foi possível abrir a conversa.',true)}}
function renderMessages(){return state.messages.map(m=>`<div class="bubble ${m.sender_id===state.user.id?'mine':''}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="empty">Inicia a conversa.</div>'}
async function sendMessage(e,proposalId,receiverId){e.preventDefault();const body=$('chatInput').value.trim();if(!body)return;try{await api('messages','',{method:'POST',body:JSON.stringify({proposal_id:proposalId,sender_id:state.user.id,receiver_id:receiverId,body})});await openChat(proposalId,receiverId)}catch{toast('Não foi possível enviar a mensagem.',true)}}

function adCard(a){return `<article class="ad-card">${a.image_url?`<img src="${esc(a.image_url)}" alt="">`:''}<span class="ad-label">PATROCINADO</span><div class="card-body"><span class="tag yellow">${esc(a.package_name||'VITRINE')}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><div class="meta"><span>📍 ${esc(a.target_location||'Moçambique')}</span><span>◎ ${esc(a.target_category||'Todos os negócios')}</span></div>${a.cta_url?`<a class="btn primary link-btn" href="${safeUrl(a.cta_url)}" target="_blank" rel="noopener">Saber mais</a>`:''}</div></article>`}
function renderAds(){$('adsFeed').innerHTML=state.ads.map(adCard).join('')||'<div class="empty">Ainda não existem campanhas ativas. Sê a primeira empresa em destaque.</div>'}
function safeUrl(v){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?esc(u.href):'#'}catch{return'#'}}
function openAdForm(){if(!requireAuth())return;openModal(`<h2>Criar Link Ads</h2><p>A campanha ficará ativa após o envio nesta versão inicial.</p><form onsubmit="submitAd(event)"><label>Pacote<select id="adPackage"><option>Impulso</option><option selected>Vitrine</option><option>Campanha</option></select></label><label>Título<input id="adTitle" required maxlength="100"></label><label>Descrição<textarea id="adDescription" required maxlength="500"></textarea></label><label>Categoria do público<select id="adCategory"><option value="">Todos os negócios</option>${CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Localização alvo<input id="adLocation" placeholder="Ex.: Maputo"></label><label>Link ou WhatsApp<input id="adUrl" type="url" placeholder="https://..."></label><label>Imagem<input id="adImage" type="file" accept="image/*"></label><button class="btn primary">Criar campanha</button></form>`)}
async function submitAd(e){e.preventDefault();try{const image_url=await uploadImage($('adImage').files[0],'ad-images');await api('advertisements','',{method:'POST',body:JSON.stringify({owner_id:state.user.id,package_name:$('adPackage').value,title:$('adTitle').value.trim(),description:$('adDescription').value.trim(),target_category:$('adCategory').value,target_location:$('adLocation').value.trim(),cta_url:$('adUrl').value.trim(),image_url,status:'active'})});closeModal();toast('Campanha criada com sucesso.');await loadPublicData();showView('ads')}catch(err){console.error(err);toast('Não foi possível criar a campanha.',true)}}
