const SUPABASE_URL='https://bfrofclxcjpufqpfyqiz.supabase.co';
const SUPABASE_KEY='sb_publishable_oXyVQBSbjW64hotxW2G-BA_akx34fk1';
const CATEGORIES=['Agricultura','Alimentação','Comércio','Construção','Educação','Eventos','Finanças','Saúde','Serviços','Tecnologia','Transporte','Turismo'];
const state={session:null,user:null,profile:null,opportunities:[],ads:[],favorites:new Set(),likes:[],comments:[],likedOpportunities:new Set(),proposals:[],messages:[],unreadMessages:0,notificationTimer:null};
const $=id=>document.getElementById(id);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const sessionKey='link_direto_session_v2';

document.addEventListener('DOMContentLoaded',async()=>{
  fillCategories();
  updatePublishPreview();
  initTechInteractions();
  try{state.session=JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{}
  if(state.session?.access_token){await restoreSession();if(state.user)startNotificationPolling()}
  setInterval(()=>{if(state.session?.refresh_token)refreshSession()},40*60*1000);
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
});

function initTechInteractions(){
  const updateNetwork=()=>{const subtitle=$('headerSubtitle');if(!subtitle)return;subtitle.textContent=navigator.onLine?'Sistema online • oportunidades perto de ti':'Sem ligação • tenta novamente';document.body.classList.toggle('is-offline',!navigator.onLine)};
  updateNetwork();window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);
  document.addEventListener('click',event=>{const button=event.target.closest('button,.btn');if(!button||button.disabled)return;if(navigator.vibrate)navigator.vibrate(8);if(!button.matches('.btn,.choice,.account,.tabs button,.icon-btn,.notification-panel button'))return;const rect=button.getBoundingClientRect(),size=Math.max(rect.width,rect.height)*1.8,ripple=document.createElement('i');ripple.className='tech-ripple';ripple.style.width=ripple.style.height=`${size}px`;ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;button.appendChild(ripple);setTimeout(()=>ripple.remove(),550)});
}

function fillCategories(){
  const options=CATEGORIES.map(c=>`<option>${c}</option>`).join('');
  $('pCategory').innerHTML=options;$('businessCategory').innerHTML=options;
  $('searchCategory').innerHTML='<option value="">Todas categorias</option>'+options;
}
function enterApp(){$('splash').classList.add('hidden');$('app').classList.remove('hidden');loadPublicData()}
function showView(name,button){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+name).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'));(button||document.querySelector(`[data-view="${name}"]`))?.classList.add('active');scrollTo(0,0);if(name==='connect')loadConnect().then(()=>markMessagesSeen());if(name==='profile')renderProfile()}
function openPublish(type='tenho'){showView('publish');document.querySelector(`input[name="ptype"][value="${type}"]`).checked=true;if(!state.user)openAuth()}
function handleAccountClick(){state.user?showView('profile'):openAuth()}
function toast(message,error=false){const t=$('toast');t.textContent=message;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',3200)}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden');$('modalContent').innerHTML=''}
function authHeaders(json=true){const h={apikey:SUPABASE_KEY};if(json)h['Content-Type']='application/json';if(state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;return h}
async function api(table,query='',options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`,{...options,headers:{...authHeaders(options.body instanceof FormData?false:true),...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}

function openAuth(mode='login'){
  openModal(`<div class="auth-intro"><span class="auth-lock">⌾</span><div><h2>Conta empresarial</h2><p>${mode==='login'?'Continua as tuas conexões.':'Cria a identidade digital do teu negócio.'}</p></div></div><div class="tabs"><button class="${mode==='login'?'active':''}" onclick="openAuth('login')">Entrar</button><button class="${mode==='signup'?'active':''}" onclick="openAuth('signup')">Criar conta</button></div><form onsubmit="${mode==='login'?'login':'signup'}(event)">${mode==='signup'?'<label>Nome do negócio<input id="authBusiness" required maxlength="80" placeholder="Ex.: Maputo Soluções"></label>':''}<label>E-mail<input id="authEmail" type="email" required autocomplete="email" placeholder="nome@empresa.com"></label><label>Senha<div class="password-wrap"><input id="authPassword" type="password" required minlength="6" autocomplete="${mode==='login'?'current-password':'new-password'}" placeholder="Mínimo de 6 caracteres"><button type="button" onclick="togglePassword()">MOSTRAR</button></div></label><div class="auth-note"><span>✓</span><span>Os teus dados de conta são protegidos. Nunca partilhamos a tua senha.</span></div><button class="btn primary">${mode==='login'?'Entrar na minha conta':'Criar conta gratuita'}</button>${mode==='login'?'<button class="text-action" type="button" onclick="openPasswordReset()">Esqueci a minha senha</button>':''}</form>`)
}
function togglePassword(){const input=$('authPassword'),button=input?.nextElementSibling;if(!input)return;input.type=input.type==='password'?'text':'password';if(button)button.textContent=input.type==='password'?'MOSTRAR':'OCULTAR'}
function openPasswordReset(){openModal(`<div class="auth-intro"><span class="auth-lock">↺</span><div><h2>Recuperar senha</h2><p>Enviaremos um acesso seguro para o teu e-mail.</p></div></div><form onsubmit="requestPasswordReset(event)"><label>E-mail da conta<input id="resetEmail" type="email" required autocomplete="email" placeholder="nome@empresa.com"></label><button class="btn primary">Enviar acesso</button><button class="text-action" type="button" onclick="openAuth('login')">Voltar para entrar</button></form>`)}
async function requestPasswordReset(e){e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='A enviar...';try{const redirect=`${location.origin}${location.pathname}`;const r=await fetch(`${SUPABASE_URL}/auth/v1/recover?redirect_to=${encodeURIComponent(redirect)}`,{method:'POST',headers:authHeaders(),body:JSON.stringify({email:$('resetEmail').value.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message);openModal('<div class="auth-success"><span class="auth-lock">✓</span><h2>Verifica o teu e-mail</h2><p class="muted">Enviámos as instruções para criares uma nova senha.</p><button class="btn primary" onclick="closeModal()">Entendido</button></div>')}catch(err){toast(readableError(err),true);button.disabled=false;button.textContent='Enviar acesso'}}
async function signup(e){e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='A criar conta...';try{const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:'POST',headers:authHeaders(),body:JSON.stringify({email:$('authEmail').value.trim(),password:$('authPassword').value,data:{business_name:$('authBusiness').value.trim()}})});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.message);if(d.access_token){setSession(d);await afterLogin();showView('profile');toast('Conta criada com sucesso.')}else{openModal('<div class="auth-success"><span class="auth-lock">✓</span><h2>Conta criada</h2><p class="muted">Confirma o teu e-mail. Depois volta para entrar na conta.</p><button class="btn primary" onclick="openAuth(\'login\')">Ir para entrar</button></div>')}}catch(err){toast(readableError(err),true);button.disabled=false;button.textContent='Criar conta gratuita'}}
async function login(e){e.preventDefault();try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:authHeaders(),body:JSON.stringify({email:$('authEmail').value,password:$('authPassword').value})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||d.message);setSession(d);await afterLogin();toast('Sessão iniciada com sucesso.')}catch(err){toast(readableError(err),true)}}
function setSession(d){state.session=d;state.user=d.user;localStorage.setItem(sessionKey,JSON.stringify(d))}
async function refreshSession(){if(!state.session?.refresh_token)return false;try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.session.refresh_token})});const d=await r.json();if(!r.ok)throw new Error();setSession(d);return true}catch{return false}}
async function restoreSession(){try{let r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(false)});if(!r.ok&&await refreshSession())r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(false)});if(!r.ok)throw new Error();state.user=await r.json();await loadProfile();updateAccountUI()}catch{localStorage.removeItem(sessionKey);state.session=null;state.user=null}}
async function afterLogin(){closeModal();await loadProfile();await loadFavorites();updateAccountUI();renderProfile();loadPublicData();startNotificationPolling()}
async function logout(){try{await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:authHeaders(false)})}catch{}stopNotificationPolling();localStorage.removeItem(sessionKey);state.session=null;state.user=null;state.profile=null;state.favorites.clear();state.likedOpportunities.clear();state.unreadMessages=0;updateNotificationBadge();updateAccountUI();renderProfile();showView('home');toast('Sessão terminada.')}
function updateAccountUI(){$('accountButton').textContent=state.profile?.business_name?.split(' ')[0]||'Entrar'}
function readableError(err){const s=String(err.message||err);if(s.includes('Invalid login'))return'E-mail ou senha incorretos.';if(s.includes('already registered'))return'Este e-mail já está registado.';if(s.includes('rate limit'))return'Tentaste muitas vezes. Aguarda alguns minutos.';return'Não foi possível concluir. Confirma os dados e tenta novamente.'}

async function loadProfile(){if(!state.user)return;try{const d=await api('profiles',`?id=eq.${state.user.id}&select=*`);state.profile=d?.[0]||null;if(!state.profile){await api('profiles','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:state.user.id,business_name:state.user.user_metadata?.business_name||'Meu negócio'})});const p=await api('profiles',`?id=eq.${state.user.id}&select=*`);state.profile=p?.[0]}}catch(err){console.error(err)}}
function setAvatar(element,url,name='LD'){if(!element)return;const initials=(name||'LD').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();element.textContent=initials;if(url){element.style.backgroundImage=`url("${String(url).replace(/["\\]/g,'')}")`;element.classList.add('has-image')}else{element.style.backgroundImage='';element.classList.remove('has-image')}}
function previewBusinessAvatar(e){const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){toast('A imagem deve ter menos de 5 MB.',true);e.target.value='';return}setAvatar($('profileAvatar'),URL.createObjectURL(file),$('businessName').value)}
function renderProfile(){const logged=!!state.user;$('profileGuest').classList.toggle('hidden',logged);$('profileForm').classList.toggle('hidden',!logged);if(!logged)return;const p=state.profile||{};$('businessName').value=p.business_name||'';$('businessCategory').value=p.category||CATEGORIES[0];$('businessLocation').value=p.location||'';$('businessPhone').value=p.phone||'';$('businessBio').value=p.bio||'';$('profileName').textContent=p.business_name||'Meu negócio';setAvatar($('profileAvatar'),p.avatar_url,p.business_name);if($('profileEmail'))$('profileEmail').textContent=state.user?.email||'Conta empresarial';if($('profileVerified'))$('profileVerified').textContent=state.user?.email_confirmed_at?'✓ E-mail confirmado':'E-mail por confirmar';if($('cardCategory'))$('cardCategory').textContent=p.category||'Categoria';if($('cardLocation'))$('cardLocation').textContent=p.location||'Moçambique';const score=40+(p.category?10:0)+(p.location?10:0)+(p.phone?10:0)+(p.bio?10:0)+(p.avatar_url?10:0);$('profileScore').textContent=`Link Score ${score}`;if($('profileProgress'))$('profileProgress').style.width=`${score}%`}
async function saveProfile(e){e.preventDefault();if(!requireAuth())return;const button=e.submitter;button.disabled=true;button.textContent='A guardar...';try{let avatar_url=state.profile?.avatar_url||null;const avatarFile=$('businessAvatar').files?.[0];if(avatarFile)avatar_url=await uploadImage(avatarFile);const body={business_name:$('businessName').value.trim(),category:$('businessCategory').value,location:$('businessLocation').value.trim(),phone:$('businessPhone').value.trim(),bio:$('businessBio').value.trim(),avatar_url,updated_at:new Date().toISOString()};await api('profiles',`?id=eq.${state.user.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});state.profile={...state.profile,...body};$('businessAvatar').value='';updateAccountUI();renderProfile();toast('Perfil atualizado com sucesso.')}catch(err){console.error(err);toast('Não foi possível guardar o perfil.',true)}finally{button.disabled=false;button.textContent='Guardar perfil'}}
function requireAuth(){if(state.user)return true;openAuth();toast('Entra primeiro na tua conta.');return false}

async function loadPublicData(){try{const [opps,ads,likes,comments]=await Promise.all([api('opportunities','?select=*&order=created_at.desc&limit=100'),api('advertisements','?select=*&status=eq.active&order=created_at.desc&limit=20'),api('opportunity_likes','?select=user_id,opportunity_id&limit=5000'),api('opportunity_comments','?select=*&order=created_at.asc&limit=5000')]);state.opportunities=opps||[];state.ads=ads||[];state.likes=likes||[];state.comments=comments||[];state.likedOpportunities=new Set(state.user?state.likes.filter(x=>x.user_id===state.user.id).map(x=>String(x.opportunity_id)):[]);if(state.user)await loadFavorites();renderHome();renderSearch();renderAds()}catch(err){console.error(err);$('homeFeed').innerHTML='<div class="empty">Não foi possível carregar. Executa primeiro o ficheiro ATUALIZAR_SUPABASE_COMPLETO.sql.</div>'}}
async function loadFavorites(){if(!state.user)return;try{const d=await api('favorites',`?user_id=eq.${state.user.id}&select=opportunity_id`);state.favorites=new Set((d||[]).map(x=>String(x.opportunity_id)))}catch{}}
function likeCount(id){return state.likes.filter(x=>String(x.opportunity_id)===String(id)).length}
function commentCount(id){return state.comments.filter(x=>String(x.opportunity_id)===String(id)).length}
function opportunityCard(o){const saved=state.favorites.has(String(o.id)),liked=state.likedOpportunities.has(String(o.id));const mine=state.user&&o.user_id===state.user.id;const media=o.video_url?`<video class="card-media" src="${esc(o.video_url)}" controls playsinline preload="metadata"></video>`:o.image_url?`<img class="card-media" src="${esc(o.image_url)}" alt="Imagem da publicação" loading="lazy">`:'';return `<article class="card">${media}<div class="card-body"><div class="card-top"><span class="tag ${o.type==='tenho'?'green':''}">${esc((o.type||'preciso').toUpperCase())} • ${esc(o.category)}</span>${o.status==='closed'?'<span class="tag">Fechado</span>':''}</div><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div class="meta"><span>📍 ${esc(o.location)}</span><span>⏱ ${formatDate(o.created_at)}</span></div><div class="social-actions"><button class="social-btn ${liked?'active':''}" onclick="toggleLike('${o.id}')" aria-label="Gostar desta publicação">♥ <span>${likeCount(o.id)}</span></button><button class="social-btn" onclick="openComments('${o.id}')" aria-label="Abrir comentários">◌ <span>${commentCount(o.id)}</span> comentários</button></div><div class="card-actions">${mine?`<button class="btn secondary" onclick="manageOpportunity('${o.id}')">Gerir anúncio</button>`:`<button class="btn primary" onclick="openProposal('${o.id}','${o.user_id||''}')">Enviar proposta</button>`}<button class="icon-btn ${saved?'saved':''}" onclick="toggleFavorite('${o.id}')">★</button></div></div></article>`}
function renderHome(){$('homeFeed').innerHTML=state.opportunities.slice(0,6).map(opportunityCard).join('')||'<div class="empty">Ainda não existem oportunidades.</div>';$('homeAd').innerHTML=state.ads[0]?adCard(state.ads[0]):'';if($('statOpps'))$('statOpps').textContent=state.opportunities.length;if($('statAds'))$('statAds').textContent=state.ads.length}
function quickCategory(category){$('searchCategory').value=category;renderSearch()}
function updatePublishPreview(){const type=document.querySelector('input[name="ptype"]:checked')?.value?.toUpperCase()||'TENHO';const title=$('pTitle')?.value?.trim()||'O teu anúncio aparecerá aqui';const category=$('pCategory')?.value||'Categoria';const location=$('pLocation')?.value?.trim()||'Localização';if($('publishPreview'))$('publishPreview').innerHTML=`<small>${esc(type)} • ${esc(category)}</small><b>${esc(title)}</b><span>📍 ${esc(location)}</span>`}
function renderSearch(){const text=($('searchText')?.value||'').toLowerCase(),type=$('searchType')?.value||'',cat=$('searchCategory')?.value||'';const items=state.opportunities.filter(o=>(!type||o.type===type)&&(!cat||o.category===cat)&&(!text||`${o.title} ${o.description} ${o.location}`.toLowerCase().includes(text)));$('searchFeed').innerHTML=items.map(opportunityCard).join('')||'<div class="empty">Nenhuma oportunidade encontrada.</div>'}
function formatDate(v){if(!v)return'Agora';return new Date(v).toLocaleDateString('pt-PT',{day:'2-digit',month:'short'})}
async function uploadImage(file,bucket='opportunity-images'){if(!file)return null;if(!requireAuth())return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${state.user.id}/${Date.now()}-${safe}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok)throw new Error(await r.text());return`${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`}
function getVideoDuration(file){return new Promise((resolve,reject)=>{const video=document.createElement('video'),url=URL.createObjectURL(file);video.preload='metadata';video.onloadedmetadata=()=>{URL.revokeObjectURL(url);resolve(video.duration)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('video inválido'))};video.src=url})}
async function validateOpportunityMedia(file){if(!file)return null;if(file.type.startsWith('image/')){if(file.size>10*1024*1024)throw new Error('IMAGE_SIZE');return'image'}if(file.type.startsWith('video/')){if(file.size>50*1024*1024)throw new Error('VIDEO_SIZE');const duration=await getVideoDuration(file);if(!Number.isFinite(duration)||duration>60.25)throw new Error('VIDEO_DURATION');return'video'}throw new Error('MEDIA_TYPE')}
async function previewOpportunityMedia(e){const file=e.target.files?.[0],hint=$('mediaHint');if(!file){if(hint)hint.textContent='Fotografia ou vídeo opcional.';return}try{const type=await validateOpportunityMedia(file);if(hint)hint.textContent=type==='video'?`✓ Vídeo aceite • ${Math.ceil(await getVideoDuration(file))} segundos`:'✓ Fotografia pronta para publicar'}catch(err){e.target.value='';if(hint)hint.textContent='Fotografia ou vídeo opcional.';toast(err.message==='VIDEO_DURATION'?'O vídeo deve ter no máximo 60 segundos.':err.message==='VIDEO_SIZE'?'O vídeo deve ter menos de 50 MB.':'Este ficheiro não pode ser utilizado.',true)}}
async function submitOpportunity(e){e.preventDefault();if(!requireAuth())return;const button=e.submitter;button.disabled=true;button.textContent='A publicar...';try{const file=$('pMedia').files?.[0],mediaType=await validateOpportunityMedia(file);const mediaUrl=file?await uploadImage(file,'opportunity-media'):null;const body={user_id:state.user.id,type:document.querySelector('input[name="ptype"]:checked').value,title:$('pTitle').value.trim(),category:$('pCategory').value,description:$('pDescription').value.trim(),location:$('pLocation').value.trim(),image_url:mediaType==='image'?mediaUrl:null,video_url:mediaType==='video'?mediaUrl:null,status:'active'};await api('opportunities','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});e.target.reset();if($('mediaHint'))$('mediaHint').textContent='Fotografia ou vídeo opcional.';toast('Publicação criada com sucesso.');await loadPublicData();showView('home')}catch(err){console.error(err);const message=err.message==='VIDEO_DURATION'?'O vídeo deve ter no máximo 60 segundos.':err.message==='VIDEO_SIZE'?'O vídeo deve ter menos de 50 MB.':'Não foi possível publicar. Confirma a atualização do Supabase.';toast(message,true)}finally{button.disabled=false;button.textContent='Publicar agora'}}
async function toggleFavorite(id){if(!requireAuth())return;try{if(state.favorites.has(String(id))){await api('favorites',`?user_id=eq.${state.user.id}&opportunity_id=eq.${id}`,{method:'DELETE'});state.favorites.delete(String(id))}else{await api('favorites','',{method:'POST',body:JSON.stringify({user_id:state.user.id,opportunity_id:id})});state.favorites.add(String(id))}renderHome();renderSearch()}catch{toast('Não foi possível guardar o favorito.',true)}}
async function toggleLike(id){if(!requireAuth())return;try{if(state.likedOpportunities.has(String(id))){await api('opportunity_likes',`?user_id=eq.${state.user.id}&opportunity_id=eq.${id}`,{method:'DELETE'});state.likes=state.likes.filter(x=>!(x.user_id===state.user.id&&String(x.opportunity_id)===String(id)));state.likedOpportunities.delete(String(id))}else{await api('opportunity_likes','',{method:'POST',body:JSON.stringify({user_id:state.user.id,opportunity_id:id})});state.likes.push({user_id:state.user.id,opportunity_id:id});state.likedOpportunities.add(String(id))}renderHome();renderSearch()}catch{toast('Não foi possível registar o like.',true)}}
function commentsFor(id){return state.comments.filter(x=>String(x.opportunity_id)===String(id))}
function commentsMarkup(id){const items=commentsFor(id);return items.map(c=>`<div class="comment"><div><b>${esc(c.author_name||'Utilizador')}</b><small>${formatDate(c.created_at)}</small></div><p>${esc(c.body)}</p>${state.user?.id===c.user_id?`<button onclick="deleteComment('${c.id}','${id}')">Eliminar</button>`:''}</div>`).join('')||'<div class="empty">Ainda não existem comentários. Sê o primeiro.</div>'}
function openComments(id){const o=state.opportunities.find(x=>String(x.id)===String(id));openModal(`<div class="comments-head"><span>◌</span><div><h2>Comentários</h2><p>${esc(o?.title||'Publicação')}</p></div></div><div class="comments-list">${commentsMarkup(id)}</div>${state.user?`<form class="comment-form" onsubmit="submitComment(event,'${id}')"><label>O teu comentário<textarea id="commentBody" required maxlength="500" placeholder="Escreve algo útil sobre esta oportunidade..."></textarea></label><button class="btn primary">Comentar</button></form>`:'<button class="btn primary" onclick="openAuth(\'login\')">Entrar para comentar</button>'}`)}
async function submitComment(e,id){e.preventDefault();const body=$('commentBody').value.trim();if(!body)return;try{const data={opportunity_id:id,user_id:state.user.id,author_name:state.profile?.business_name||state.user.email?.split('@')[0]||'Utilizador',body};const created=await api('opportunity_comments','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});state.comments.push(created?.[0]||{...data,id:Date.now(),created_at:new Date().toISOString()});openComments(id);renderHome();renderSearch();toast('Comentário publicado.')}catch{toast('Não foi possível publicar o comentário.',true)}}
async function deleteComment(commentId,opportunityId){if(!confirm('Eliminar este comentário?'))return;try{await api('opportunity_comments',`?id=eq.${commentId}&user_id=eq.${state.user.id}`,{method:'DELETE'});state.comments=state.comments.filter(x=>String(x.id)!==String(commentId));openComments(opportunityId);renderHome();renderSearch()}catch{toast('Não foi possível eliminar o comentário.',true)}}
function manageOpportunity(id){const o=state.opportunities.find(x=>String(x.id)===String(id));openModal(`<h2>Gerir publicação</h2><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><button class="btn secondary" onclick="setOpportunityStatus('${id}','${o.status==='closed'?'active':'closed'}')">${o.status==='closed'?'Reabrir':'Marcar como concluída'}</button><button class="btn ghost" onclick="deleteOpportunity('${id}')">Eliminar publicação</button>`)}
async function setOpportunityStatus(id,status){try{await api('opportunities',`?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status})});closeModal();await loadPublicData();toast('Publicação atualizada.')}catch{toast('Não foi possível atualizar.',true)}}
async function deleteOpportunity(id){if(!confirm('Eliminar esta publicação?'))return;try{await api('opportunities',`?id=eq.${id}`,{method:'DELETE'});closeModal();await loadPublicData();toast('Publicação eliminada.')}catch{toast('Não foi possível eliminar.',true)}}

function openProposal(opportunityId,ownerId){if(!requireAuth())return;if(!ownerId){toast('Esta publicação antiga não tem proprietário associado.',true);return}const o=state.opportunities.find(x=>String(x.id)===String(opportunityId));openModal(`<h2>Proposta Direta</h2><p>Para: <b>${esc(o?.title||'Oportunidade')}</b></p><form onsubmit="submitProposal(event,'${opportunityId}','${ownerId}')"><label>Mensagem<textarea id="proposalMessage" required placeholder="Explica o que podes oferecer..."></textarea></label><label>Valor estimado (opcional)<input id="proposalPrice" inputmode="decimal" placeholder="Ex.: 5 000 MZN"></label><label>Prazo (opcional)<input id="proposalDeadline" placeholder="Ex.: Entrega em 3 dias"></label><button class="btn primary">Enviar proposta</button></form>`)}
async function submitProposal(e,opportunityId,ownerId){e.preventDefault();const o=state.opportunities.find(x=>String(x.id)===String(opportunityId));try{await api('proposals','',{method:'POST',body:JSON.stringify({opportunity_id:opportunityId,opportunity_title:o?.title||'Oportunidade',sender_id:state.user.id,owner_id:ownerId,message:$('proposalMessage').value.trim(),price:$('proposalPrice').value.trim(),deadline:$('proposalDeadline').value.trim(),status:'pending'})});closeModal();toast('Proposta enviada.');loadConnect()}catch{toast('Não foi possível enviar a proposta.',true)}}
function seenMessagesKey(){return state.user?`link_direto_messages_seen_${state.user.id}`:'link_direto_messages_seen'}
function checkedMessagesKey(){return state.user?`link_direto_messages_checked_${state.user.id}`:'link_direto_messages_checked'}
function startNotificationPolling(){if(!state.user)return;stopNotificationPolling();const now=new Date().toISOString();if(!localStorage.getItem(seenMessagesKey()))localStorage.setItem(seenMessagesKey(),now);if(!localStorage.getItem(checkedMessagesKey()))localStorage.setItem(checkedMessagesKey(),now);updateNotificationPanel();pollNotifications(true);state.notificationTimer=setInterval(()=>pollNotifications(false),8000)}
function stopNotificationPolling(){if(state.notificationTimer)clearInterval(state.notificationTimer);state.notificationTimer=null}
function updateNotificationBadge(){const badge=$('connectBadge');if(!badge)return;badge.textContent=state.unreadMessages>99?'99+':String(state.unreadMessages);badge.classList.toggle('hidden',!state.unreadMessages)}
function updateNotificationPanel(){const panel=$('notificationPanel'),button=$('notificationButton');if(!panel||!button)return;panel.classList.toggle('hidden',!state.user);const enabled='Notification'in window&&Notification.permission==='granted';panel.classList.toggle('enabled',enabled);button.textContent=enabled?'Ativadas':'Ativar'}
async function enableNotifications(){if(!('Notification'in window)){toast('Este navegador não permite alertas. O contador no Connect continuará ativo.',true);return}try{const permission=await Notification.requestPermission();updateNotificationPanel();toast(permission==='granted'?'Notificações ativadas.':'Permissão de notificações não autorizada.',permission!=='granted')}catch{toast('Não foi possível ativar as notificações.',true)}}
async function showMessageNotification(message){const text=(message.body||'Recebeste uma nova mensagem.').slice(0,100);if(!document.querySelector('#view-connect.active'))toast(`Nova mensagem: ${text}`);if(!('Notification'in window)||Notification.permission!=='granted')return;try{if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.ready;await registration.showNotification('Nova mensagem no Link Direto',{body:text,icon:'./icon-192.png',badge:'./icon-192.png',tag:`message-${message.id}`,data:{url:`${location.pathname}?v=8`}})}else new Notification('Nova mensagem no Link Direto',{body:text,icon:'./icon-192.png'})}catch{}}
async function pollNotifications(silent=false){if(!state.user)return;try{const seen=localStorage.getItem(seenMessagesKey())||new Date().toISOString();const checked=localStorage.getItem(checkedMessagesKey())||seen;const [unread,newItems]=await Promise.all([api('messages',`?receiver_id=eq.${state.user.id}&created_at=gt.${encodeURIComponent(seen)}&select=id&order=created_at.asc&limit=100`),api('messages',`?receiver_id=eq.${state.user.id}&created_at=gt.${encodeURIComponent(checked)}&select=id,body,created_at&order=created_at.asc&limit=20`)]);state.unreadMessages=(unread||[]).length;updateNotificationBadge();if(!silent&&newItems?.length)await showMessageNotification(newItems[newItems.length-1]);localStorage.setItem(checkedMessagesKey(),new Date().toISOString())}catch(err){console.error('notification check',err)}}
function markMessagesSeen(){if(!state.user)return;const now=new Date().toISOString();localStorage.setItem(seenMessagesKey(),now);localStorage.setItem(checkedMessagesKey(),now);state.unreadMessages=0;updateNotificationBadge()}
async function loadConnect(){if(!state.user){$('connectContent').innerHTML='<div class="empty">Entra na tua conta para veres propostas e conversas.</div>';return}try{state.proposals=await api('proposals',`?or=(sender_id.eq.${state.user.id},owner_id.eq.${state.user.id})&order=created_at.desc` )||[];$('pendingCount').textContent=state.proposals.filter(p=>p.status==='pending').length;$('acceptedCount').textContent=state.proposals.filter(p=>p.status==='accepted').length;$('messageCount').textContent=state.proposals.filter(p=>p.status==='accepted').length;$('connectContent').innerHTML=state.proposals.map(proposalCard).join('')||'<div class="empty">Ainda não existem propostas.</div>'}catch(err){console.error(err);$('connectContent').innerHTML='<div class="empty">Não foi possível carregar as propostas.</div>'}}
function proposalCard(p){const incoming=p.owner_id===state.user.id;return `<article class="card"><div class="card-body"><div class="card-top"><span class="tag ${p.status==='accepted'?'green':p.status==='pending'?'yellow':''}">${p.status==='pending'?'PENDENTE':p.status==='accepted'?'ACEITE':'RECUSADA'}</span><small>${incoming?'Recebida':'Enviada'}</small></div><h3>${esc(p.opportunity_title)}</h3><p>${esc(p.message)}</p><div class="meta"><span>${esc(p.price||'Valor a combinar')}</span><span>${esc(p.deadline||'Prazo a combinar')}</span></div><div class="card-actions">${incoming&&p.status==='pending'?`<button class="btn primary" onclick="updateProposal('${p.id}','accepted')">Aceitar</button><button class="icon-btn" onclick="updateProposal('${p.id}','rejected')">×</button>`:p.status==='accepted'?`<button class="btn primary" onclick="openChat('${p.id}','${incoming?p.sender_id:p.owner_id}')">Abrir conversa</button>`:'<button class="btn secondary" disabled>A aguardar resposta</button>'}</div></div></article>`}
async function updateProposal(id,status){try{await api('proposals',`?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status})});toast(status==='accepted'?'Proposta aceite. Chat aberto.':'Proposta recusada.');loadConnect()}catch{toast('Não foi possível atualizar.',true)}}
async function openChat(proposalId,otherId){const proposal=state.proposals.find(p=>String(p.id)===String(proposalId));try{state.messages=await api('messages',`?proposal_id=eq.${proposalId}&order=created_at.asc`)||[];openModal(`<h2>Sala de Negócio</h2><p>${esc(proposal?.opportunity_title||'Conversa')}</p><div id="chatMessages" class="chat">${renderMessages()}</div><form onsubmit="sendMessage(event,'${proposalId}','${otherId}')"><label>Mensagem<input id="chatInput" required autocomplete="off" placeholder="Escreve uma mensagem..."></label><button class="btn primary">Enviar</button></form>`);setTimeout(()=>{const c=$('chatMessages');c.scrollTop=c.scrollHeight},0)}catch{toast('Não foi possível abrir a conversa.',true)}}
function renderMessages(){return state.messages.map(m=>`<div class="bubble ${m.sender_id===state.user.id?'mine':''}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="empty">Inicia a conversa.</div>'}
async function sendMessage(e,proposalId,receiverId){e.preventDefault();const body=$('chatInput').value.trim();if(!body)return;try{await api('messages','',{method:'POST',body:JSON.stringify({proposal_id:proposalId,sender_id:state.user.id,receiver_id:receiverId,body})});await openChat(proposalId,receiverId)}catch{toast('Não foi possível enviar a mensagem.',true)}}

function adCard(a){return `<article class="ad-card">${a.image_url?`<img src="${esc(a.image_url)}" alt="">`:''}<span class="ad-label">PATROCINADO</span><div class="card-body"><span class="tag yellow">${esc(a.package_name||'VITRINE')}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><div class="meta"><span>📍 ${esc(a.target_location||'Moçambique')}</span><span>◎ ${esc(a.target_category||'Todos os negócios')}</span></div>${a.cta_url?`<a class="btn primary link-btn" href="${safeUrl(a.cta_url)}" target="_blank" rel="noopener">Saber mais</a>`:''}</div></article>`}
function renderAds(){$('adsFeed').innerHTML=state.ads.map(adCard).join('')||'<div class="empty">Ainda não existem campanhas ativas. Sê a primeira empresa em destaque.</div>'}
function safeUrl(v){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?esc(u.href):'#'}catch{return'#'}}
function openAdForm(){if(!requireAuth())return;openModal(`<h2>Criar Link Ads</h2><p>A campanha ficará ativa após o envio nesta versão inicial.</p><form onsubmit="submitAd(event)"><label>Pacote<select id="adPackage"><option>Impulso</option><option selected>Vitrine</option><option>Campanha</option></select></label><label>Título<input id="adTitle" required maxlength="100"></label><label>Descrição<textarea id="adDescription" required maxlength="500"></textarea></label><label>Categoria do público<select id="adCategory"><option value="">Todos os negócios</option>${CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Localização alvo<input id="adLocation" placeholder="Ex.: Maputo"></label><label>Link ou WhatsApp<input id="adUrl" type="url" placeholder="https://..."></label><label>Imagem<input id="adImage" type="file" accept="image/*"></label><button class="btn primary">Criar campanha</button></form>`)}
async function submitAd(e){e.preventDefault();try{const image_url=await uploadImage($('adImage').files[0],'ad-images');await api('advertisements','',{method:'POST',body:JSON.stringify({owner_id:state.user.id,package_name:$('adPackage').value,title:$('adTitle').value.trim(),description:$('adDescription').value.trim(),target_category:$('adCategory').value,target_location:$('adLocation').value.trim(),cta_url:$('adUrl').value.trim(),image_url,status:'active'})});closeModal();toast('Campanha criada com sucesso.');await loadPublicData();showView('ads')}catch(err){console.error(err);toast('Não foi possível criar a campanha.',true)}}
