-- LINK DIRETO CONNECT - ATUALIZACAO COMPLETA
-- Pode executar este ficheiro mais de uma vez.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  business_name text not null default 'Meu negócio',
  category text,
  location text,
  phone text,
  bio text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, business_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'business_name','Meu negócio'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.opportunities add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.opportunities add column if not exists image_url text;
alter table public.opportunities add column if not exists status text not null default 'active';

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, opportunity_id)
);

create table if not exists public.proposals (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  opportunity_title text not null,
  sender_id uuid not null references auth.users(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  message text not null,
  price text,
  deadline text,
  status text not null default 'pending' check(status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  proposal_id bigint not null references public.proposals(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  package_name text not null default 'Vitrine',
  title text not null,
  description text not null,
  image_url text,
  target_category text,
  target_location text,
  cta_url text,
  status text not null default 'active' check(status in ('pending','active','paused','rejected')),
  views bigint not null default 0,
  clicks bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.opportunities enable row level security;
alter table public.favorites enable row level security;
alter table public.proposals enable row level security;
alter table public.messages enable row level security;
alter table public.advertisements enable row level security;

drop policy if exists "Publicações visíveis para todos" on public.opportunities;
drop policy if exists "Qualquer visitante pode publicar" on public.opportunities;
drop policy if exists opportunities_read on public.opportunities;
drop policy if exists opportunities_insert on public.opportunities;
drop policy if exists opportunities_update on public.opportunities;
drop policy if exists opportunities_delete on public.opportunities;
create policy opportunities_read on public.opportunities for select to anon, authenticated using (true);
create policy opportunities_insert on public.opportunities for insert to authenticated with check (auth.uid() = user_id);
create policy opportunities_update on public.opportunities for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy opportunities_delete on public.opportunities for delete to authenticated using (auth.uid() = user_id);

drop policy if exists profiles_read on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
create policy profiles_read on public.profiles for select to anon, authenticated using (true);
create policy profiles_insert on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy profiles_update on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists favorites_own on public.favorites;
create policy favorites_own on public.favorites for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists proposals_read on public.proposals;
drop policy if exists proposals_insert on public.proposals;
drop policy if exists proposals_update on public.proposals;
create policy proposals_read on public.proposals for select to authenticated using (auth.uid() = sender_id or auth.uid() = owner_id);
create policy proposals_insert on public.proposals for insert to authenticated with check (auth.uid() = sender_id and sender_id <> owner_id);
create policy proposals_update on public.proposals for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists messages_read on public.messages;
drop policy if exists messages_insert on public.messages;
create policy messages_read on public.messages for select to authenticated using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy messages_insert on public.messages for insert to authenticated with check (auth.uid() = sender_id and sender_id <> receiver_id);

drop policy if exists ads_read on public.advertisements;
drop policy if exists ads_insert on public.advertisements;
drop policy if exists ads_update on public.advertisements;
drop policy if exists ads_delete on public.advertisements;
create policy ads_read on public.advertisements for select to anon, authenticated using (status='active' or auth.uid()=owner_id);
create policy ads_insert on public.advertisements for insert to authenticated with check (auth.uid()=owner_id);
create policy ads_update on public.advertisements for update to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy ads_delete on public.advertisements for delete to authenticated using (auth.uid()=owner_id);

insert into storage.buckets (id,name,public) values ('opportunity-images','opportunity-images',true) on conflict (id) do update set public=true;
insert into storage.buckets (id,name,public) values ('ad-images','ad-images',true) on conflict (id) do update set public=true;

drop policy if exists public_images_read on storage.objects;
drop policy if exists user_images_insert on storage.objects;
drop policy if exists user_images_update on storage.objects;
drop policy if exists user_images_delete on storage.objects;
create policy public_images_read on storage.objects for select to anon, authenticated using (bucket_id in ('opportunity-images','ad-images'));
create policy user_images_insert on storage.objects for insert to authenticated with check (bucket_id in ('opportunity-images','ad-images') and (storage.foldername(name))[1]=auth.uid()::text);
create policy user_images_update on storage.objects for update to authenticated using (bucket_id in ('opportunity-images','ad-images') and owner_id=auth.uid()::text);
create policy user_images_delete on storage.objects for delete to authenticated using (bucket_id in ('opportunity-images','ad-images') and owner_id=auth.uid()::text);

