-- LINK DIRETO CONNECT — chamadas WebRTC V32
-- Executar uma vez no Supabase > SQL Editor

create extension if not exists pgcrypto;

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid null,
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  call_type text not null default 'voice' check (call_type in ('voice','video')),
  status text not null default 'preparing' check (status in ('preparing','ringing','accepted','rejected','ended','missed')),
  offer jsonb,
  answer jsonb,
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz
);

create index if not exists call_sessions_callee_status_idx on public.call_sessions(callee_id,status,created_at desc);
create index if not exists call_sessions_caller_idx on public.call_sessions(caller_id,created_at desc);

create table if not exists public.call_ice_candidates (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.call_sessions(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  candidate jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists call_ice_candidates_call_idx on public.call_ice_candidates(call_id,id);

alter table public.call_sessions enable row level security;
alter table public.call_ice_candidates enable row level security;

drop policy if exists "call participants select sessions" on public.call_sessions;
create policy "call participants select sessions" on public.call_sessions for select to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "caller creates call" on public.call_sessions;
create policy "caller creates call" on public.call_sessions for insert to authenticated
with check (auth.uid() = caller_id and caller_id <> callee_id);

drop policy if exists "call participants update sessions" on public.call_sessions;
create policy "call participants update sessions" on public.call_sessions for update to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id)
with check (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "call participants select ice" on public.call_ice_candidates;
create policy "call participants select ice" on public.call_ice_candidates for select to authenticated
using (exists (select 1 from public.call_sessions c where c.id=call_id and (c.caller_id=auth.uid() or c.callee_id=auth.uid())));

drop policy if exists "call participants insert ice" on public.call_ice_candidates;
create policy "call participants insert ice" on public.call_ice_candidates for insert to authenticated
with check (auth.uid()=sender_id and exists (select 1 from public.call_sessions c where c.id=call_id and (c.caller_id=auth.uid() or c.callee_id=auth.uid())));

grant select,insert,update on public.call_sessions to authenticated;
grant select,insert on public.call_ice_candidates to authenticated;
grant usage,select on all sequences in schema public to authenticated;
